// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for the
/// [BatchRecognize][google.cloud.speech.v2.Speech.BatchRecognize]
/// method.
///
/// [google.cloud.speech.v2.Speech.BatchRecognize]: <doc:Speech/batchRecognize(request:)>
public struct BatchRecognizeRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the Recognizer to use during recognition. The
  /// expected format is
  /// `projects/{project}/locations/{location}/recognizers/{recognizer}`. The
  /// {recognizer} segment may be set to `_` to use an empty implicit Recognizer.
  public var recognizer: Swift.String = Swift.String()

  /// Features and audio metadata to use for the Automatic Speech Recognition.
  /// This field in combination with the
  /// [config_mask][google.cloud.speech.v2.BatchRecognizeRequest.config_mask]
  /// field can be used to override parts of the
  /// [default_recognition_config][google.cloud.speech.v2.Recognizer.default_recognition_config]
  /// of the Recognizer resource.
  ///
  /// [google.cloud.speech.v2.BatchRecognizeRequest.config_mask]: <doc:BatchRecognizeRequest/configMask>
  /// [google.cloud.speech.v2.Recognizer.default_recognition_config]: <doc:Recognizer/defaultRecognitionConfig>
  public var config: RecognitionConfig? = nil

  /// The list of fields in
  /// [config][google.cloud.speech.v2.BatchRecognizeRequest.config] that override
  /// the values in the
  /// [default_recognition_config][google.cloud.speech.v2.Recognizer.default_recognition_config]
  /// of the recognizer during this recognition request. If no mask is provided,
  /// all given fields in
  /// [config][google.cloud.speech.v2.BatchRecognizeRequest.config] override the
  /// values in the recognizer for this recognition request. If a mask is
  /// provided, only the fields listed in the mask override the config in the
  /// recognizer for this recognition request. If a wildcard (`*`) is provided,
  /// [config][google.cloud.speech.v2.BatchRecognizeRequest.config] completely
  /// overrides and replaces the config in the recognizer for this recognition
  /// request.
  ///
  /// [google.cloud.speech.v2.BatchRecognizeRequest.config]: <doc:BatchRecognizeRequest/config>
  /// [google.cloud.speech.v2.Recognizer.default_recognition_config]: <doc:Recognizer/defaultRecognitionConfig>
  public var configMask: GoogleCloudWkt.FieldMask? = nil

  /// Audio files with file metadata for ASR.
  /// The maximum number of files allowed to be specified is 15.
  public var files: [BatchRecognizeFileMetadata] = []

  /// Configuration options for where to output the transcripts of each file.
  public var recognitionOutputConfig: RecognitionOutputConfig? = nil

  /// Processing strategy to use for this request.
  public var processingStrategy: BatchRecognizeRequest.ProcessingStrategy =
    BatchRecognizeRequest.ProcessingStrategy()

  /// Initialize a new instance of `BatchRecognizeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchRecognizeRequest().with { $0.recognizer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible processing strategies for batch requests.
  public enum ProcessingStrategy: Codable, Equatable, Sendable {
    /// Default value for the processing strategy. The request is processed as
    /// soon as its received.
    case unspecified
    /// If selected, processes the request during lower utilization periods for a
    /// price discount. The request is fulfilled within 24 hours.
    case dynamicBatching
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .dynamicBatching: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROCESSING_STRATEGY_UNSPECIFIED"
      case .dynamicBatching: return "DYNAMIC_BATCHING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROCESSING_STRATEGY_UNSPECIFIED": self = .unspecified
      case "DYNAMIC_BATCHING": self = .dynamicBatching
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .dynamicBatching
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .dynamicBatching: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.BatchRecognizeRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
