// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Final results written to Cloud Storage.
public struct CloudStorageResult: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The Cloud Storage URI to which recognition results were written.
  public var uri: Swift.String = Swift.String()

  /// The Cloud Storage URI to which recognition results were written as VTT
  /// formatted captions. This is populated only when `VTT` output is requested.
  public var vttFormatUri: Swift.String = Swift.String()

  /// The Cloud Storage URI to which recognition results were written as SRT
  /// formatted captions. This is populated only when `SRT` output is requested.
  public var srtFormatUri: Swift.String = Swift.String()

  /// Initialize a new instance of `CloudStorageResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudStorageResult().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.CloudStorageResult"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
