// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for the
/// [CreatePhraseSet][google.cloud.speech.v2.Speech.CreatePhraseSet] method.
///
/// [google.cloud.speech.v2.Speech.CreatePhraseSet]: <doc:SpeechClient/createPhraseSet(request:options:)>
public struct CreatePhraseSetRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The PhraseSet to create.
  public var phraseSet: PhraseSet? = nil

  /// If set, validate the request and preview the PhraseSet, but do not
  /// actually create it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// The ID to use for the PhraseSet, which will become the final component of
  /// the PhraseSet's resource name.
  ///
  /// This value should be 4-63 characters, and valid characters
  /// are /[a-z][0-9]-/.
  public var phraseSetId: Swift.String = Swift.String()

  /// Required. The project and location where this PhraseSet will be created.
  /// The expected format is `projects/{project}/locations/{location}`.
  public var parent: Swift.String = Swift.String()

  /// Initialize a new instance of `CreatePhraseSetRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreatePhraseSetRequest().with { $0.phraseSet = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.CreatePhraseSetRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
