// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Denoiser config. May not be supported for all models and may
/// have no effect.
public struct DenoiserConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Denoise audio before sending to the transcription model.
  public var denoiseAudio: Swift.Bool = Swift.Bool()

  /// Signal-to-Noise Ratio (SNR) threshold for the denoiser. Here SNR means the
  /// loudness of the speech signal. Audio with an SNR below this threshold,
  /// meaning the speech is too quiet, will be prevented from being sent to the
  /// transcription model.
  ///
  /// If snr_threshold=0, no filtering will be applied.
  public var snrThreshold: Swift.Float = Swift.Float()

  /// Initialize a new instance of `DenoiserConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DenoiserConfig().with { $0.denoiseAudio = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.DenoiserConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
