// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Final results returned inline in the recognition response.
public struct InlineResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The transcript for the audio file.
  public var transcript: BatchRecognizeResults? = nil

  /// The transcript for the audio file as VTT formatted captions. This is
  /// populated only when `VTT` output is requested.
  public var vttCaptions: Swift.String = Swift.String()

  /// The transcript for the audio file as SRT formatted captions. This is
  /// populated only when `SRT` output is requested.
  public var srtCaptions: Swift.String = Swift.String()

  /// Initialize a new instance of `InlineResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InlineResult().with { $0.transcript = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.InlineResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
