// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudGax
import GoogleCloudWkt

/// Response message for the
/// [ListRecognizers][google.cloud.speech.v2.Speech.ListRecognizers] method.
///
/// [google.cloud.speech.v2.Speech.ListRecognizers]: <doc:SpeechClient/listRecognizers(request:options:)>
public struct ListRecognizersResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The list of requested Recognizers.
  public var recognizers: [Recognizer] = []

  /// A token, which can be sent as
  /// [page_token][google.cloud.speech.v2.ListRecognizersRequest.page_token] to
  /// retrieve the next page. If this field is omitted, there are no subsequent
  /// pages. This token expires after 72 hours.
  ///
  /// [google.cloud.speech.v2.ListRecognizersRequest.page_token]: <doc:ListRecognizersRequest/pageToken>
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListRecognizersResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListRecognizersResponse().with { $0.recognizers = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.ListRecognizersResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [Recognizer] {
    return self.recognizers
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
