// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for the
/// [ListRecognizers][google.cloud.speech.v2.Speech.ListRecognizers] method.
///
/// [google.cloud.speech.v2.Speech.ListRecognizers]: <doc:SpeechClient/listRecognizers(request:)>
public struct ListRecognizersRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project and location of Recognizers to list. The expected
  /// format is `projects/{project}/locations/{location}`.
  public var parent: Swift.String = Swift.String()

  /// The maximum number of Recognizers to return. The service may return fewer
  /// than this value. If unspecified, at most 5 Recognizers will be returned.
  /// The maximum value is 100; values above 100 will be coerced to 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token, received from a previous
  /// [ListRecognizers][google.cloud.speech.v2.Speech.ListRecognizers] call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// [ListRecognizers][google.cloud.speech.v2.Speech.ListRecognizers] must match
  /// the call that provided the page token.
  ///
  /// [google.cloud.speech.v2.Speech.ListRecognizers]: <doc:SpeechClient/listRecognizers(request:)>
  public var pageToken: Swift.String = Swift.String()

  /// Whether, or not, to show resources that have been deleted.
  public var showDeleted: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ListRecognizersRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListRecognizersRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.ListRecognizersRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
