// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for the
/// [ListCustomClasses][google.cloud.speech.v2.Speech.ListCustomClasses] method.
///
/// [google.cloud.speech.v2.Speech.ListCustomClasses]: <doc:SpeechClient/listCustomClasses(request:options:)>
public struct ListCustomClassesRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The project and location of CustomClass resources to list. The
  /// expected format is `projects/{project}/locations/{location}`.
  public var parent: Swift.String = Swift.String()

  /// Number of results per requests. A valid page_size ranges from 0 to 100
  /// inclusive. If the page_size is zero or unspecified, a page size of 5 will
  /// be chosen. If the page size exceeds 100, it will be coerced down to 100.
  /// Note that a call might return fewer results than the requested page size.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token, received from a previous
  /// [ListCustomClasses][google.cloud.speech.v2.Speech.ListCustomClasses] call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// [ListCustomClasses][google.cloud.speech.v2.Speech.ListCustomClasses] must
  /// match the call that provided the page token.
  ///
  /// [google.cloud.speech.v2.Speech.ListCustomClasses]: <doc:SpeechClient/listCustomClasses(request:options:)>
  public var pageToken: Swift.String = Swift.String()

  /// Whether, or not, to show resources that have been deleted.
  public var showDeleted: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ListCustomClassesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCustomClassesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.ListCustomClassesRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
