// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for the format of the results stored to `output`.
public struct OutputFormatConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Configuration for the native output format. If this field is set or if no
  /// other output format field is set, then transcripts will be written to the
  /// sink in the native format.
  public var native: NativeOutputFileFormatConfig? = nil

  /// Configuration for the VTT output format. If this field is set, then
  /// transcripts will be written to the sink in the VTT format.
  public var vtt: VttOutputFileFormatConfig? = nil

  /// Configuration for the SRT output format. If this field is set, then
  /// transcripts will be written to the sink in the SRT format.
  public var srt: SrtOutputFileFormatConfig? = nil

  /// Initialize a new instance of `OutputFormatConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OutputFormatConfig().with { $0.native = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.OutputFormatConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
