// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// PhraseSet for biasing in speech recognition. A PhraseSet is used to provide
/// "hints" to the speech recognizer to favor specific words and phrases in the
/// results.
public struct PhraseSet: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource name of the PhraseSet.
  /// Format: `projects/{project}/locations/{location}/phraseSets/{phrase_set}`.
  public var name: Swift.String = Swift.String()

  /// Output only. System-assigned unique identifier for the PhraseSet.
  public var uid: Swift.String = Swift.String()

  /// A list of word and phrases.
  public var phrases: [PhraseSet.Phrase] = []

  /// Hint Boost. Positive value will increase the probability that a specific
  /// phrase will be recognized over other similar sounding phrases. The higher
  /// the boost, the higher the chance of false positive recognition as well.
  /// Valid `boost` values are between 0 (exclusive) and 20. We recommend using a
  /// binary search approach to finding the optimal value for your use case as
  /// well as adding phrases both with and without boost to your requests.
  public var boost: Swift.Float = Swift.Float()

  /// User-settable, human-readable name for the PhraseSet. Must be 63
  /// characters or less.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The PhraseSet lifecycle state.
  public var state: PhraseSet.State = PhraseSet.State()

  /// Output only. Creation time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The most recent time this resource was modified.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which this resource was requested for deletion.
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which this resource will be purged.
  public var expireTime: GoogleCloudWkt.Timestamp? = nil

  /// Allows users to store small amounts of arbitrary data.
  /// Both the key and the value must be 63 characters or less each.
  /// At most 100 annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. This checksum is computed by the server based on the value of
  /// other fields. This may be sent on update, undelete, and delete requests to
  /// ensure the client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Output only. Whether or not this PhraseSet is in the process of being
  /// updated.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Output only. The [KMS key
  /// name](https://cloud.google.com/kms/docs/resource-hierarchy#keys) with which
  /// the PhraseSet is encrypted. The expected format is
  /// `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}`.
  public var kmsKeyName: Swift.String = Swift.String()

  /// Output only. The [KMS key version
  /// name](https://cloud.google.com/kms/docs/resource-hierarchy#key_versions)
  /// with which the PhraseSet is encrypted. The expected format is
  /// `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}/cryptoKeyVersions/{crypto_key_version}`.
  public var kmsKeyVersionName: Swift.String = Swift.String()

  /// Initialize a new instance of `PhraseSet`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PhraseSet().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A Phrase contains words and phrase "hints" so that the speech recognition
  /// is more likely to recognize them. This can be used to improve the accuracy
  /// for specific words and phrases, for example, if specific commands are
  /// typically spoken by the user. This can also be used to add additional words
  /// to the vocabulary of the recognizer.
  ///
  /// List items can also include CustomClass references containing groups of
  /// words that represent common concepts that occur in natural language.
  public struct Phrase: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The phrase itself.
    public var value: Swift.String = Swift.String()

    /// Hint Boost. Overrides the boost set at the phrase set level.
    /// Positive value will increase the probability that a specific phrase will
    /// be recognized over other similar sounding phrases. The higher the boost,
    /// the higher the chance of false positive recognition as well. Negative
    /// boost values would correspond to anti-biasing. Anti-biasing is not
    /// enabled, so negative boost values will return an error. Boost values must
    /// be between 0 and 20. Any values outside that range will return an error.
    /// We recommend using a binary search approach to finding the optimal value
    /// for your use case as well as adding phrases both with and without boost
    /// to your requests.
    public var boost: Swift.Float = Swift.Float()

    /// Initialize a new instance of `Phrase`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Phrase().with { $0.value = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.speech.v2.PhraseSet.Phrase"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Set of states that define the lifecycle of a PhraseSet.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.  This is only used/useful for distinguishing
    /// unset values.
    case unspecified
    /// The normal and active state.
    case active
    /// This PhraseSet has been deleted.
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 2
      case .deleted: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 2: self = .active
      case 4: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(2)
      case .deleted: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.PhraseSet"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
