// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for the
/// [Recognize][google.cloud.speech.v2.Speech.Recognize] method.
///
/// [google.cloud.speech.v2.Speech.Recognize]: <doc:SpeechClient/recognize(request:options:)>
public struct RecognizeResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Sequential list of transcription results corresponding to sequential
  /// portions of audio.
  public var results: [SpeechRecognitionResult] = []

  /// Metadata about the recognition.
  public var metadata: RecognitionResponseMetadata? = nil

  /// Initialize a new instance of `RecognizeResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RecognizeResponse().with { $0.results = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.RecognizeResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
