// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Available recognition features.
public struct RecognitionFeatures: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// If set to `true`, the server will attempt to filter out profanities,
  /// replacing all but the initial character in each filtered word with
  /// asterisks, for instance, "f***". If set to `false` or omitted, profanities
  /// won't be filtered out.
  public var profanityFilter: Swift.Bool = Swift.Bool()

  /// If `true`, the top result includes a list of words and the start and end
  /// time offsets (timestamps) for those words. If `false`, no word-level time
  /// offset information is returned. The default is `false`.
  public var enableWordTimeOffsets: Swift.Bool = Swift.Bool()

  /// If `true`, the top result includes a list of words and the confidence for
  /// those words. If `false`, no word-level confidence information is returned.
  /// The default is `false`.
  public var enableWordConfidence: Swift.Bool = Swift.Bool()

  /// If `true`, adds punctuation to recognition result hypotheses. This feature
  /// is only available in select languages. The default `false` value does not
  /// add punctuation to result hypotheses.
  public var enableAutomaticPunctuation: Swift.Bool = Swift.Bool()

  /// The spoken punctuation behavior for the call. If `true`, replaces spoken
  /// punctuation with the corresponding symbols in the request. For example,
  /// "how are you question mark" becomes "how are you?". See
  /// https://cloud.google.com/speech-to-text/docs/spoken-punctuation for
  /// support. If `false`, spoken punctuation is not replaced.
  public var enableSpokenPunctuation: Swift.Bool = Swift.Bool()

  /// The spoken emoji behavior for the call. If `true`, adds spoken emoji
  /// formatting for the request. This will replace spoken emojis with the
  /// corresponding Unicode symbols in the final transcript. If `false`, spoken
  /// emojis are not replaced.
  public var enableSpokenEmojis: Swift.Bool = Swift.Bool()

  /// Mode for recognizing multi-channel audio.
  public var multiChannelMode: RecognitionFeatures.MultiChannelMode =
    RecognitionFeatures.MultiChannelMode()

  /// Configuration to enable speaker diarization. To enable diarization, set
  /// this field to an empty SpeakerDiarizationConfig message.
  public var diarizationConfig: SpeakerDiarizationConfig? = nil

  /// Maximum number of recognition hypotheses to be returned.
  /// The server may return fewer than `max_alternatives`.
  /// Valid values are `0`-`30`. A value of `0` or `1` will return a maximum of
  /// one. If omitted, will return a maximum of one.
  public var maxAlternatives: Swift.Int32 = Swift.Int32()

  /// Optional. Configuration to enable custom prompt for chirp3.
  public var customPromptConfig: CustomPromptConfig? = nil

  /// Initialize a new instance of `RecognitionFeatures`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RecognitionFeatures().with { $0.profanityFilter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Options for how to recognize multi-channel audio.
  public enum MultiChannelMode: Codable, Equatable, Sendable {
    /// Default value for the multi-channel mode. If the audio contains
    /// multiple channels, only the first channel will be transcribed; other
    /// channels will be ignored.
    case unspecified
    /// If selected, each channel in the provided audio is transcribed
    /// independently. This cannot be selected if the selected
    /// [model][google.cloud.speech.v2.Recognizer.model] is `latest_short`.
    ///
    /// [google.cloud.speech.v2.Recognizer.model]: <doc:Recognizer/model>
    case separateRecognitionPerChannel
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .separateRecognitionPerChannel: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MULTI_CHANNEL_MODE_UNSPECIFIED"
      case .separateRecognitionPerChannel: return "SEPARATE_RECOGNITION_PER_CHANNEL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MultiChannelMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MULTI_CHANNEL_MODE_UNSPECIFIED": self = .unspecified
      case "SEPARATE_RECOGNITION_PER_CHANNEL": self = .separateRecognitionPerChannel
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MultiChannelMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .separateRecognitionPerChannel
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .separateRecognitionPerChannel: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.RecognitionFeatures"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
