// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Recognizer message. Stores recognition configuration and metadata.
public struct Recognizer: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource name of the Recognizer.
  /// Format: `projects/{project}/locations/{location}/recognizers/{recognizer}`.
  public var name: Swift.String = Swift.String()

  /// Output only. System-assigned unique identifier for the Recognizer.
  public var uid: Swift.String = Swift.String()

  /// User-settable, human-readable name for the Recognizer. Must be 63
  /// characters or less.
  public var displayName: Swift.String = Swift.String()

  /// Optional. This field is now deprecated. Prefer the
  /// [`model`][google.cloud.speech.v2.RecognitionConfig.model] field in the
  /// [`RecognitionConfig`][google.cloud.speech.v2.RecognitionConfig] message.
  ///
  /// Which model to use for recognition requests. Select the model best suited
  /// to your domain to get best results.
  ///
  /// Guidance for choosing which model to use can be found in the [Transcription
  /// Models
  /// Documentation](https://cloud.google.com/speech-to-text/v2/docs/transcription-model)
  /// and the models supported in each region can be found in the [Table Of
  /// Supported
  /// Models](https://cloud.google.com/speech-to-text/v2/docs/speech-to-text-supported-languages).
  ///
  /// [google.cloud.speech.v2.RecognitionConfig]: <doc:RecognitionConfig>
  /// [google.cloud.speech.v2.RecognitionConfig.model]: <doc:RecognitionConfig/model>
  @available(*, deprecated)
  public var model: Swift.String = Swift.String()

  /// Optional. This field is now deprecated. Prefer the
  /// [`language_codes`][google.cloud.speech.v2.RecognitionConfig.language_codes]
  /// field in the
  /// [`RecognitionConfig`][google.cloud.speech.v2.RecognitionConfig] message.
  ///
  /// The language of the supplied audio as a
  /// [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) language tag.
  ///
  /// Supported languages for each model are listed in the [Table of Supported
  /// Models](https://cloud.google.com/speech-to-text/v2/docs/speech-to-text-supported-languages).
  ///
  /// If additional languages are provided, recognition result will contain
  /// recognition in the most likely language detected. The recognition result
  /// will include the language tag of the language detected in the audio.
  /// When you create or update a Recognizer, these values are
  /// stored in normalized BCP-47 form. For example, "en-us" is stored as
  /// "en-US".
  ///
  /// [google.cloud.speech.v2.RecognitionConfig]: <doc:RecognitionConfig>
  /// [google.cloud.speech.v2.RecognitionConfig.language_codes]: <doc:RecognitionConfig/languageCodes>
  @available(*, deprecated)
  public var languageCodes: [Swift.String] = []

  /// Default configuration to use for requests with this Recognizer.
  /// This can be overwritten by inline configuration in the
  /// [RecognizeRequest.config][google.cloud.speech.v2.RecognizeRequest.config]
  /// field.
  ///
  /// [google.cloud.speech.v2.RecognizeRequest.config]: <doc:RecognizeRequest/config>
  public var defaultRecognitionConfig: RecognitionConfig? = nil

  /// Allows users to store small amounts of arbitrary data.
  /// Both the key and the value must be 63 characters or less each.
  /// At most 100 annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. The Recognizer lifecycle state.
  public var state: Recognizer.State = Recognizer.State()

  /// Output only. Creation time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The most recent time this Recognizer was modified.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which this Recognizer was requested for deletion.
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which this Recognizer will be purged.
  public var expireTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. This checksum is computed by the server based on the value of
  /// other fields. This may be sent on update, undelete, and delete requests to
  /// ensure the client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Output only. Whether or not this Recognizer is in the process of being
  /// updated.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Output only. The [KMS key
  /// name](https://cloud.google.com/kms/docs/resource-hierarchy#keys) with which
  /// the Recognizer is encrypted. The expected format is
  /// `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}`.
  public var kmsKeyName: Swift.String = Swift.String()

  /// Output only. The [KMS key version
  /// name](https://cloud.google.com/kms/docs/resource-hierarchy#key_versions)
  /// with which the Recognizer is encrypted. The expected format is
  /// `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}/cryptoKeyVersions/{crypto_key_version}`.
  public var kmsKeyVersionName: Swift.String = Swift.String()

  /// Initialize a new instance of `Recognizer`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Recognizer().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Set of states that define the lifecycle of a Recognizer.
  public enum State: Codable, Equatable, Sendable {
    /// The default value. This value is used if the state is omitted.
    case unspecified
    /// The Recognizer is active and ready for use.
    case active
    /// This Recognizer has been deleted.
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 2
      case .deleted: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 2: self = .active
      case 4: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(2)
      case .deleted: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.Recognizer"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
