// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class SpeechRetry: SpeechStub {
    let inner: any SpeechStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any SpeechStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createRecognizer(
      request: CreateRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateRecognizerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createRecognizer(request: r, options: o)
        })
    }

    public func listRecognizers(
      request: ListRecognizersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.ListRecognizersResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListRecognizersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSpeechV2.ListRecognizersResponse
          in
          return try await self.inner.listRecognizers(request: r, options: o)
        })
    }

    public func getRecognizer(
      request: GetRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.Recognizer {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetRecognizerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSpeechV2.Recognizer
          in
          return try await self.inner.getRecognizer(request: r, options: o)
        })
    }

    public func updateRecognizer(
      request: UpdateRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateRecognizerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateRecognizer(request: r, options: o)
        })
    }

    public func deleteRecognizer(
      request: DeleteRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteRecognizerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteRecognizer(request: r, options: o)
        })
    }

    public func undeleteRecognizer(
      request: UndeleteRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UndeleteRecognizerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.undeleteRecognizer(request: r, options: o)
        })
    }

    public func recognize(
      request: RecognizeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.RecognizeResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RecognizeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSpeechV2.RecognizeResponse
          in
          return try await self.inner.recognize(request: r, options: o)
        })
    }

    public func batchRecognize(
      request: BatchRecognizeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchRecognizeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchRecognize(request: r, options: o)
        })
    }

    public func getConfig(
      request: GetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.Config {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSpeechV2.Config
          in
          return try await self.inner.getConfig(request: r, options: o)
        })
    }

    public func updateConfig(
      request: UpdateConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.Config {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSpeechV2.Config
          in
          return try await self.inner.updateConfig(request: r, options: o)
        })
    }

    public func createCustomClass(
      request: CreateCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateCustomClassRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCustomClass(request: r, options: o)
        })
    }

    public func listCustomClasses(
      request: ListCustomClassesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.ListCustomClassesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListCustomClassesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSpeechV2.ListCustomClassesResponse
          in
          return try await self.inner.listCustomClasses(request: r, options: o)
        })
    }

    public func getCustomClass(
      request: GetCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.CustomClass {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetCustomClassRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSpeechV2.CustomClass
          in
          return try await self.inner.getCustomClass(request: r, options: o)
        })
    }

    public func updateCustomClass(
      request: UpdateCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateCustomClassRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCustomClass(request: r, options: o)
        })
    }

    public func deleteCustomClass(
      request: DeleteCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteCustomClassRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCustomClass(request: r, options: o)
        })
    }

    public func undeleteCustomClass(
      request: UndeleteCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UndeleteCustomClassRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.undeleteCustomClass(request: r, options: o)
        })
    }

    public func createPhraseSet(
      request: CreatePhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreatePhraseSetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPhraseSet(request: r, options: o)
        })
    }

    public func listPhraseSets(
      request: ListPhraseSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.ListPhraseSetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListPhraseSetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSpeechV2.ListPhraseSetsResponse
          in
          return try await self.inner.listPhraseSets(request: r, options: o)
        })
    }

    public func getPhraseSet(
      request: GetPhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.PhraseSet {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPhraseSetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSpeechV2.PhraseSet
          in
          return try await self.inner.getPhraseSet(request: r, options: o)
        })
    }

    public func updatePhraseSet(
      request: UpdatePhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdatePhraseSetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePhraseSet(request: r, options: o)
        })
    }

    public func deletePhraseSet(
      request: DeletePhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeletePhraseSetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePhraseSet(request: r, options: o)
        })
    }

    public func undeletePhraseSet(
      request: UndeletePhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UndeletePhraseSetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.undeletePhraseSet(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
