// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class SpeechTransport: SpeechStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://speech.googleapis.com",
      )
    }

    public func createRecognizer(
      request: CreateRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v2/\(pathVariable0)/recognizers"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      query.append(contentsOf: try encoder.encode(request.recognizerId, prefix: "recognizerId"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.recognizer {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listRecognizers(
      request: ListRecognizersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.ListRecognizersResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v2/\(pathVariable0)/recognizers"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.showDeleted, prefix: "showDeleted"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSpeechV2.ListRecognizersResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getRecognizer(
      request: GetRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.Recognizer {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSpeechV2.Recognizer.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateRecognizer(
      request: UpdateRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.recognizer.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.recognizer.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.recognizer {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteRecognizer(
      request: DeleteRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.etag, prefix: "etag"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func undeleteRecognizer(
      request: UndeleteRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0):undelete"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func recognize(
      request: RecognizeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.RecognizeResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.recognizer as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.recognizer' is not set or is empty")
        }
        return "/v2/\(pathVariable0):recognize"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudSpeechV2.RecognizeResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func batchRecognize(
      request: BatchRecognizeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.recognizer as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.recognizer' is not set or is empty")
        }
        return "/v2/\(pathVariable0):batchRecognize"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getConfig(
      request: GetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.Config {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSpeechV2.Config.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateConfig(
      request: UpdateConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.Config {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.config.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.config.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.config {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudSpeechV2.Config.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createCustomClass(
      request: CreateCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v2/\(pathVariable0)/customClasses"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      query.append(contentsOf: try encoder.encode(request.customClassId, prefix: "customClassId"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.customClass {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listCustomClasses(
      request: ListCustomClassesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.ListCustomClassesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v2/\(pathVariable0)/customClasses"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.showDeleted, prefix: "showDeleted"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSpeechV2.ListCustomClassesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getCustomClass(
      request: GetCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.CustomClass {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSpeechV2.CustomClass.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateCustomClass(
      request: UpdateCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.customClass.map({ $0.name }), !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.custom_class.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.customClass {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteCustomClass(
      request: DeleteCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.etag, prefix: "etag"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func undeleteCustomClass(
      request: UndeleteCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0):undelete"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createPhraseSet(
      request: CreatePhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v2/\(pathVariable0)/phraseSets"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      query.append(contentsOf: try encoder.encode(request.phraseSetId, prefix: "phraseSetId"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.phraseSet {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listPhraseSets(
      request: ListPhraseSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.ListPhraseSetsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v2/\(pathVariable0)/phraseSets"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.showDeleted, prefix: "showDeleted"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSpeechV2.ListPhraseSetsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getPhraseSet(
      request: GetPhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.PhraseSet {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSpeechV2.PhraseSet.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updatePhraseSet(
      request: UpdatePhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.phraseSet.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.phrase_set.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.phraseSet {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deletePhraseSet(
      request: DeletePhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.etag, prefix: "etag"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func undeletePhraseSet(
      request: UndeletePhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0):undelete"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)/locations"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.ListLocationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.Location.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)/operations"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(
        contentsOf: try encoder.encode(request.returnPartialSuccess, prefix: "returnPartialSuccess")
      )
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.ListOperationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v2/\(pathVariable0):cancel"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
