// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Provides "hints" to the speech recognizer to favor specific words and phrases
/// in the results. PhraseSets can be specified as an inline resource, or a
/// reference to an existing PhraseSet resource.
public struct SpeechAdaptation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A list of inline or referenced PhraseSets.
  public var phraseSets: [SpeechAdaptation.AdaptationPhraseSet] = []

  /// A list of inline CustomClasses. Existing CustomClass resources can be
  /// referenced directly in a PhraseSet.
  public var customClasses: [CustomClass] = []

  /// Initialize a new instance of `SpeechAdaptation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SpeechAdaptation().with { $0.phraseSets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A biasing PhraseSet, which can be either a string referencing the name of
  /// an existing PhraseSets resource, or an inline definition of a PhraseSet.
  public struct AdaptationPhraseSet: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var value: OneOf_Value? = nil

    /// Initialize a new instance of `AdaptationPhraseSet`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AdaptationPhraseSet().with { $0.phraseSet = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case phraseSet = "phraseSet"
      case inlinePhraseSet = "inlinePhraseSet"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var value: OneOf_Value? = nil
      let valueCheckAndSet = {
        if value != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'value'"))
        }
        value = $0
      }
      if let phraseSet = try container.decodeIfPresent(Swift.String.self, forKey: .phraseSet) {
        try valueCheckAndSet(.phraseSet(phraseSet))
      }
      if let inlinePhraseSet = try container.decodeIfPresent(
        PhraseSet?.self, forKey: .inlinePhraseSet)
      {
        try valueCheckAndSet(.inlinePhraseSet(inlinePhraseSet))
      }
      self.value = value
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.value {
        switch choice {
        case .phraseSet(let value):
          try container.encode(value, forKey: .phraseSet)
        case .inlinePhraseSet(let value):
          try container.encode(value, forKey: .inlinePhraseSet)
        }
      }
    }

    public enum OneOf_Value: Codable, Equatable, Sendable {
      /// The name of an existing PhraseSet resource. The user must have read
      /// access to the resource and it must not be deleted.
      case phraseSet(Swift.String)
      /// An inline defined PhraseSet.
      indirect case inlinePhraseSet(PhraseSet?)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.speech.v2.SpeechAdaptation.AdaptationPhraseSet"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.speech.v2.SpeechAdaptation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
