// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol SpeechStub: Sendable {
    func createRecognizer(
      request: CreateRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRecognizers(
      request: ListRecognizersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.ListRecognizersResponse

    func getRecognizer(
      request: GetRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.Recognizer

    func updateRecognizer(
      request: UpdateRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteRecognizer(
      request: DeleteRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func undeleteRecognizer(
      request: UndeleteRecognizerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func recognize(
      request: RecognizeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.RecognizeResponse

    func batchRecognize(
      request: BatchRecognizeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getConfig(
      request: GetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.Config

    func updateConfig(
      request: UpdateConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.Config

    func createCustomClass(
      request: CreateCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listCustomClasses(
      request: ListCustomClassesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.ListCustomClassesResponse

    func getCustomClass(
      request: GetCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.CustomClass

    func updateCustomClass(
      request: UpdateCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCustomClass(
      request: DeleteCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func undeleteCustomClass(
      request: UndeleteCustomClassRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createPhraseSet(
      request: CreatePhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listPhraseSets(
      request: ListPhraseSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.ListPhraseSetsResponse

    func getPhraseSet(
      request: GetPhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSpeechV2.PhraseSet

    func updatePhraseSet(
      request: UpdatePhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deletePhraseSet(
      request: DeletePhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func undeletePhraseSet(
      request: UndeletePhraseSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
