// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A speech recognition result corresponding to a portion of the audio.
public struct SpeechRecognitionResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// May contain one or more recognition hypotheses. These alternatives are
  /// ordered in terms of accuracy, with the top (first) alternative being the
  /// most probable, as ranked by the recognizer.
  public var alternatives: [SpeechRecognitionAlternative] = []

  /// For multi-channel audio, this is the channel number corresponding to the
  /// recognized result for the audio from that channel.
  /// For `audio_channel_count` = `N`, its output values can range from `1` to
  /// `N`.
  public var channelTag: Swift.Int32 = Swift.Int32()

  /// Time offset of the end of this result relative to the beginning of the
  /// audio.
  public var resultEndOffset: GoogleCloudWkt.Duration? = nil

  /// Output only. The [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt)
  /// language tag of the language in this result. This language code was
  /// detected to have the most likelihood of being spoken in the audio.
  public var languageCode: Swift.String = Swift.String()

  /// Initialize a new instance of `SpeechRecognitionResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SpeechRecognitionResult().with { $0.alternatives = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.speech.v2.SpeechRecognitionResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
