// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Available recognition features specific to streaming recognition requests.
public struct StreamingRecognitionFeatures: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// If `true`, responses with voice activity speech events will be returned as
  /// they are detected.
  public var enableVoiceActivityEvents: Swift.Bool = Swift.Bool()

  /// Whether or not to stream interim results to the client. If set to true,
  /// interim results will be streamed to the client. Otherwise, only the final
  /// response will be streamed back.
  public var interimResults: Swift.Bool = Swift.Bool()

  /// If set, the server will automatically close the stream after the specified
  /// duration has elapsed after the last VOICE_ACTIVITY speech event has been
  /// sent. The field `voice_activity_events` must also be set to true.
  public var voiceActivityTimeout: StreamingRecognitionFeatures.VoiceActivityTimeout? = nil

  /// Optional. Endpointing sensitivity for this stream.
  public var endpointingSensitivity: StreamingRecognitionFeatures.EndpointingSensitivity =
    StreamingRecognitionFeatures.EndpointingSensitivity()

  /// Initialize a new instance of `StreamingRecognitionFeatures`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StreamingRecognitionFeatures().with { $0.enableVoiceActivityEvents = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Events that a timeout can be set on for voice activity.
  public struct VoiceActivityTimeout: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Duration to timeout the stream if no speech begins. If this is set and
    /// no speech is detected in this duration at the start of the stream, the
    /// server will close the stream.
    public var speechStartTimeout: GoogleCloudWKT.Duration? = nil

    /// Duration to timeout the stream after speech ends. If this is set and no
    /// speech is detected in this duration after speech was detected, the server
    /// will close the stream.
    public var speechEndTimeout: GoogleCloudWKT.Duration? = nil

    /// Initialize a new instance of `VoiceActivityTimeout`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VoiceActivityTimeout().with { $0.speechStartTimeout = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.speech.v2.StreamingRecognitionFeatures.VoiceActivityTimeout"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Endpointing sensitivity is intended for applications that want to minimize
  /// result latency, possibly at the expense of quality. Some utterances may be
  /// broken up into multiple fragments.
  public enum EndpointingSensitivity: Codable, Equatable, Sendable {
    /// If no value is specified, the values for
    /// ENDPOINTING_SENSITIVITY_STANDARD will be used.
    case unspecified
    /// Standard sensitivity, no optimization for latency.
    case standard
    /// Super short sensitivity, optimized for super short utterances like single
    /// words ("Yes", "No", "Hello", etc.) or a single phrase, command or short
    /// query (e.g. "check balance", "five dollars", "call Mom").
    case supershort
    /// Short sensitivity, optimized for short utterances like single sentences.
    /// (e.g. "Remind me to call the dentist tomorrow morning at nine",
    /// "Navigate to the nearest coffee shop that is currently open")
    case short
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .standard: return 1
      case .supershort: return 2
      case .short: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ENDPOINTING_SENSITIVITY_UNSPECIFIED"
      case .standard: return "ENDPOINTING_SENSITIVITY_STANDARD"
      case .supershort: return "ENDPOINTING_SENSITIVITY_SUPERSHORT"
      case .short: return "ENDPOINTING_SENSITIVITY_SHORT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EndpointingSensitivity/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ENDPOINTING_SENSITIVITY_UNSPECIFIED": self = .unspecified
      case "ENDPOINTING_SENSITIVITY_STANDARD": self = .standard
      case "ENDPOINTING_SENSITIVITY_SUPERSHORT": self = .supershort
      case "ENDPOINTING_SENSITIVITY_SHORT": self = .short
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EndpointingSensitivity/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .standard
      case 2: self = .supershort
      case 3: self = .short
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .standard: return try container.encode(1)
      case .supershort: return try container.encode(2)
      case .short: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.StreamingRecognitionFeatures"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
