// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for the
/// [StreamingRecognize][google.cloud.speech.v2.Speech.StreamingRecognize]
/// method. Multiple
/// [StreamingRecognizeRequest][google.cloud.speech.v2.StreamingRecognizeRequest]
/// messages are sent in one call.
///
/// If the [Recognizer][google.cloud.speech.v2.Recognizer] referenced by
/// [recognizer][google.cloud.speech.v2.StreamingRecognizeRequest.recognizer]
/// contains a fully specified request configuration then the stream may only
/// contain messages with only
/// [audio][google.cloud.speech.v2.StreamingRecognizeRequest.audio] set.
///
/// Otherwise the first message must contain a
/// [recognizer][google.cloud.speech.v2.StreamingRecognizeRequest.recognizer] and
/// a
/// [streaming_config][google.cloud.speech.v2.StreamingRecognizeRequest.streaming_config]
/// message that together fully specify the request configuration and must not
/// contain [audio][google.cloud.speech.v2.StreamingRecognizeRequest.audio]. All
/// subsequent messages must only have
/// [audio][google.cloud.speech.v2.StreamingRecognizeRequest.audio] set.
///
/// [google.cloud.speech.v2.Recognizer]: <doc:Recognizer>
/// [google.cloud.speech.v2.Speech.StreamingRecognize]: <doc:SpeechClient/streamingRecognize(request:)>
/// [google.cloud.speech.v2.StreamingRecognizeRequest]: <doc:StreamingRecognizeRequest>
/// [google.cloud.speech.v2.StreamingRecognizeRequest.audio]: <doc:StreamingRecognizeRequest/audio>
/// [google.cloud.speech.v2.StreamingRecognizeRequest.recognizer]: <doc:StreamingRecognizeRequest/recognizer>
/// [google.cloud.speech.v2.StreamingRecognizeRequest.streaming_config]: <doc:StreamingRecognizeRequest/streamingConfig>
public struct StreamingRecognizeRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the Recognizer to use during recognition. The
  /// expected format is
  /// `projects/{project}/locations/{location}/recognizers/{recognizer}`. The
  /// {recognizer} segment may be set to `_` to use an empty implicit Recognizer.
  public var recognizer: Swift.String = Swift.String()

  public var streamingRequest: OneOf_StreamingRequest? = nil

  /// Initialize a new instance of `StreamingRecognizeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StreamingRecognizeRequest().with { $0.recognizer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case recognizer = "recognizer"
    case streamingConfig = "streamingConfig"
    case audio = "audio"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.recognizer = try container.decode(Swift.String.self, forKey: .recognizer)

    var streamingRequest: OneOf_StreamingRequest? = nil
    let streamingRequestCheckAndSet = {
      if streamingRequest != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'streamingRequest'"))
      }
      streamingRequest = $0
    }
    if let streamingConfig = try container.decodeIfPresent(
      StreamingRecognitionConfig?.self, forKey: .streamingConfig)
    {
      try streamingRequestCheckAndSet(.streamingConfig(streamingConfig))
    }
    if let audio = try container.decodeIfPresent(Foundation.Data.self, forKey: .audio) {
      try streamingRequestCheckAndSet(.audio(audio))
    }
    self.streamingRequest = streamingRequest
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.recognizer, forKey: .recognizer)

    if let choice = self.streamingRequest {
      switch choice {
      case .streamingConfig(let value):
        try container.encode(value, forKey: .streamingConfig)
      case .audio(let value):
        try container.encode(value, forKey: .audio)
      }
    }
  }

  public enum OneOf_StreamingRequest: Codable, Equatable, Sendable {
    /// StreamingRecognitionConfig to be used in this recognition attempt.
    /// If provided, it will override the default RecognitionConfig stored in the
    /// Recognizer.
    indirect case streamingConfig(StreamingRecognitionConfig?)
    /// Inline audio bytes to be Recognized.
    /// Maximum size for this field is 15 KB per request.
    case audio(Foundation.Data)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.StreamingRecognizeRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
