// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A streaming speech recognition result corresponding to a portion of the audio
/// that is currently being processed.
public struct StreamingRecognitionResult: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// May contain one or more recognition hypotheses. These alternatives are
  /// ordered in terms of accuracy, with the top (first) alternative being the
  /// most probable, as ranked by the recognizer.
  public var alternatives: [SpeechRecognitionAlternative] = []

  /// If `false`, this
  /// [StreamingRecognitionResult][google.cloud.speech.v2.StreamingRecognitionResult]
  /// represents an interim result that may change. If `true`, this is the final
  /// time the speech service will return this particular
  /// [StreamingRecognitionResult][google.cloud.speech.v2.StreamingRecognitionResult],
  /// the recognizer will not return any further hypotheses for this portion of
  /// the transcript and corresponding audio.
  ///
  /// [google.cloud.speech.v2.StreamingRecognitionResult]: <doc:StreamingRecognitionResult>
  public var isFinal: Swift.Bool = Swift.Bool()

  /// An estimate of the likelihood that the recognizer will not change its guess
  /// about this interim result. Values range from 0.0 (completely unstable)
  /// to 1.0 (completely stable). This field is only provided for interim results
  /// ([is_final][google.cloud.speech.v2.StreamingRecognitionResult.is_final]=`false`).
  /// The default of 0.0 is a sentinel value indicating `stability` was not set.
  ///
  /// [google.cloud.speech.v2.StreamingRecognitionResult.is_final]: <doc:StreamingRecognitionResult/isFinal>
  public var stability: Swift.Float = Swift.Float()

  /// Time offset of the end of this result relative to the beginning of the
  /// audio.
  public var resultEndOffset: GoogleCloudWKT.Duration? = nil

  /// For multi-channel audio, this is the channel number corresponding to the
  /// recognized result for the audio from that channel.
  /// For
  /// `audio_channel_count` = `N`, its output values can range from `1` to `N`.
  public var channelTag: Swift.Int32 = Swift.Int32()

  /// Output only. The [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt)
  /// language tag of the language in this result. This language code was
  /// detected to have the most likelihood of being spoken in the audio.
  public var languageCode: Swift.String = Swift.String()

  /// Initialize a new instance of `StreamingRecognitionResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StreamingRecognitionResult().with { $0.alternatives = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.StreamingRecognitionResult"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
