// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Transcription normalization configuration. Use transcription normalization
/// to automatically replace parts of the transcript with phrases of your
/// choosing. For StreamingRecognize, this normalization only applies to stable
/// partial transcripts (stability > 0.8) and final transcripts.
public struct TranscriptNormalization: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A list of replacement entries. We will perform replacement with one entry
  /// at a time. For example, the second entry in ["cat" => "dog", "mountain cat"
  /// => "mountain dog"] will never be applied because we will always process the
  /// first entry before it. At most 100 entries.
  public var entries: [TranscriptNormalization.Entry] = []

  /// Initialize a new instance of `TranscriptNormalization`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TranscriptNormalization().with { $0.entries = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A single replacement configuration.
  public struct Entry: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// What to replace. Max length is 100 characters.
    public var search: Swift.String = Swift.String()

    /// What to replace with. Max length is 100 characters.
    public var replace: Swift.String = Swift.String()

    /// Whether the search is case sensitive.
    public var caseSensitive: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `Entry`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Entry().with { $0.search = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.speech.v2.TranscriptNormalization.Entry"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.speech.v2.TranscriptNormalization"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
