// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for the
/// [UndeletePhraseSet][google.cloud.speech.v2.Speech.UndeletePhraseSet]
/// method.
///
/// [google.cloud.speech.v2.Speech.UndeletePhraseSet]: <doc:SpeechClient/undeletePhraseSet(request:options:)>
public struct UndeletePhraseSetRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the PhraseSet to undelete.
  /// Format: `projects/{project}/locations/{location}/phraseSets/{phrase_set}`
  public var name: Swift.String = Swift.String()

  /// If set, validate the request and preview the undeleted PhraseSet, but do
  /// not actually undelete it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// This checksum is computed by the server based on the value of other
  /// fields. This may be sent on update, undelete, and delete requests to ensure
  /// the client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `UndeletePhraseSetRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UndeletePhraseSetRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.UndeletePhraseSetRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
