// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for the
/// [UpdatePhraseSet][google.cloud.speech.v2.Speech.UpdatePhraseSet] method.
///
/// [google.cloud.speech.v2.Speech.UpdatePhraseSet]: <doc:SpeechClient/updatePhraseSet(request:options:)>
public struct UpdatePhraseSetRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The PhraseSet to update.
  ///
  /// The PhraseSet's `name` field is used to identify the PhraseSet to update.
  /// Format: `projects/{project}/locations/{location}/phraseSets/{phrase_set}`.
  public var phraseSet: PhraseSet? = nil

  /// The list of fields to update. If empty, all non-default valued fields are
  /// considered for update. Use `*` to update the entire PhraseSet resource.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// If set, validate the request and preview the updated PhraseSet, but do not
  /// actually update it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `UpdatePhraseSetRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdatePhraseSetRequest().with { $0.phraseSet = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.speech.v2.UpdatePhraseSetRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
